CREATE TABLE teams (sport TEXT, full TEXT, short TEXT);
/* NBA */
INSERT INTO teams (sport, full, short) VALUES ('nba', 'New York Knicks', 'NY');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Orlando Magic', 'ORL');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Toronto Raptors', 'TOR');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Atlanta Hawks', 'ATL');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Philadelphia 76ers', 'PHI');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Milwaukee Bucks', 'MIL');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Boston Celtics', 'BOS');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Chicago Bulls', 'CHI');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Washington Wizards', 'WSH');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Detroit Pistons', 'DET');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Indiana Pacers', 'IND');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Cleveland Cavaliers', 'CLE');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Dallas Mavericks', 'DAL');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Memphis Grizzlies', 'MEM');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'New Orleans Pelicans', 'NO');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'San Antonio Spurs', 'SAS');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Sacramento Kings', 'SAC');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Los Angeles Clippers', 'LAC');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Charlotte Hornets', 'CHA');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Golden State Warriors', 'GS');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Los Angeles Lakers', 'LAL');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Oklahoma City Thunder', 'OKC');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Minnesota Timberwolves', 'MIN');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Miami Heat', 'MIA');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Portland Trailblazers', 'POR');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Denver Nuggets', 'DEN');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Phoenix Suns', 'PHX');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Houston Rockets', 'HOU');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Brooklyn Nets', 'BKN');
INSERT INTO teams (sport, full, short) VALUES ('nba', 'Utah Jazz', 'UTAH');
/* WNBA */
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Tulsa Shock', 'TUL');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Atlanta Dream', 'ATL');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'New York Liberty', 'NYL');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Connecticut Sun', 'CT');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Indiana Fever', 'IND');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'San Antonio Stars', 'SAS');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Minnesota Lynx', 'MIN');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Los Angeles Sparks', 'LOS');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Seattle Storm', 'SEA');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Chicago Sky', 'CHI');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Phoenix Mercury', 'PHO');
INSERT INTO teams (sport, full, short) VALUES ('wnba', 'Washington Mystics', 'WAS');
/* NFL */
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Atlanta Falcons', 'ATL');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Detroit Lions', 'DET');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'New Orleans Saints', 'NO');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Dallas Cowboys', 'DAL');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Tennessee Titans', 'TEN');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Green Bay Packers', 'GB');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Indianapolis Colts', 'IND');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Kansas City Chiefs', 'KC');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Buffalo Bills', 'BUF');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Miami Dolphins', 'MIA');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'San Diego Chargers', 'SD');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'New York Jets', 'NYJ');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Washington Redskins', 'WSH');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Philadelphia Eagles', 'PHI');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Cincinnati Bengals', 'CIN');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Pittsburgh Steelers', 'PIT');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'St. Louis Rams', 'STL');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Tampa Bay Buccaneers', 'TB');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Oakland Raiders', 'OAK');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Carolina Panthers', 'CAR');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'New England Patriots', 'NE');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Jacksonville Jaguars', 'JAX');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Minnesota Vikings', 'MIN');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Houston Texans', 'HOU');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Cleveland Browns', 'CLE');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Denver Broncos', 'DEN');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Chicago Bears', 'CHI');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Arizona Cardinals', 'ARI');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'New York Giants', 'NYG');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Baltimore Ravens', 'BAL');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'San Francisco 49ers', 'SF');
INSERT INTO teams (sport, full, short) VALUES ('nfl', 'Seattle Seahawks', 'SEA');
/* NHL */
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Los Angeles Kings', 'LA');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Boston Bruins', 'BOS');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'New Jersey Devils', 'NJ');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Pittsburgh Penguins', 'PIT');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Toronto Maple Leafs', 'TOR');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Washington Capitals', 'WSH');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Buffalo Sabres', 'BUF');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Montreal Canadiens', 'MTL');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Columbus Blue Jackets', 'CBJ');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Winnipeg Jets', 'WPG');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Phoenix Coyotes', 'ARI');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'New York Rangers', 'NYR');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Calgary Flames', 'CGY');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Chicago Blackhawks', 'CHI');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Carolina Hurricanes', 'CAR');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Philadelphia Flyers', 'PHI');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Ottawa Senators', 'OTT');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Florida Panthers', 'FLA');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Tampa Bay Lightning', 'TB');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Dallas Stars', 'DAL');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'San Jose Sharks', 'SJ');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Edmonton Oilers', 'EDM');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Colorado Avalanche', 'COL');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'New York Islanders', 'NYI');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Minnesota Wild', 'MIN');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Detroit Red Wings', 'DET');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Nashville Predators', 'NSH');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Pittsburgh Penguins', 'PIT');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'St. Louis Blues', 'STL');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Anaheim Ducks', 'ANA');
INSERT INTO teams (sport, full, short) VALUES ('nhl', 'Vancouver Canucks', 'VAN');
/* MLB */
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'New York Yankees', 'NYY');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Toronto Blue Jays', 'TOR');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Tampa Bay Rays', 'TB');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Chicago White Sox', 'CHW');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Detroit Tigers', 'DET');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Minnesota Twins', 'MIN');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Seattle Mariners', 'SEA');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Oakland Athletics', 'OAK');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Los Angeles Angels', 'LAA');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Texas Rangers', 'TEX');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Boston Red Sox', 'BOS');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Baltimore Orioles', 'BAL');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Kansas City Royals', 'KC');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Cleveland Indians', 'CLE');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Cincinnati Reds', 'CIN');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Pittsburgh Pirates', 'PIT');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Houston Astros', 'HOU');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Milwaukee Brewers', 'MIL');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'New York Mets', 'NYM');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Atlanta Braves', 'ATL');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Philadelphia Phillies', 'PHI');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Miami Marlins', 'MIA');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Washington Nationals', 'WSH');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'St. Louis Cardinals', 'STL');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Chicago Cubs', 'CHC');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Arizona Diamondbacks', 'ARI');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'San Francisco Giants', 'SF');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'San Diego Padres', 'SD');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Colorado Rockies', 'COL');
INSERT INTO teams (sport, full, short) VALUES ('mlb', 'Los Angeles Dodgers', 'LAD');
/* NCF */
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southern Illinois Salukis', 'SIU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'San Jose State Spartans', 'SJSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Sam Houston State Bearkats', 'SHSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Clemson Tigers', 'CLEM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Dakota State Bison', 'NDSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Pittsburgh Panthers', 'PITT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Arizona Wildcats', 'ARIZ');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Oklahoma State Cowboys', 'OKST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Idaho Vandals', 'IDHO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UAB Blazers', 'UAB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Mississippi State Bulldogs', 'MSST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Weber State Wildcats', 'WEB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Georgia Tech Yellow Jackets', 'GT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Vanderbilt Commodores', 'VAN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Florida International Golden Panthers', 'FIU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Brigham Young Cougars', 'BYU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Hawaii Warriors', 'HAW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Bowling Green Falcons', 'BGSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Syracuse Orange', 'SYR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Richmond Spiders', 'RICH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Rice Owls', 'RICE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Towson Tigers', 'TOWS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Northern Illinois Huskies', 'NIU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Northern Arizona Lumberjacks', 'NAU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Eastern Michigan Eagles', 'EMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Illinois State Redbirds', 'ILST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Central Michigan Chippewas', 'CMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'TCU Horned Frogs', 'TCU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas State Bobcats', 'TXST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas Tech Red Raiders', 'TTU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'LSU Tigers', 'LSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas Southern Tigers', 'TXSO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Virginia Cavaliers', 'UVA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Northwestern State Demons', 'NWST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tulsa Golden Hurricane', 'TLSA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Villanova Wildcats', 'VILL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Jackson State Tigers', 'JKST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Maine Black Bears', 'ME');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Maryland Terrapins', 'MD');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tennessee Volunteers', 'TENN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Indiana Hoosiers', 'IND');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Idaho State Bengals', 'IDST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Penn State Nittany Lions', 'PSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Sacramento State Hornets', 'CSUS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Akron Zips', 'AKR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southern Methodist Mustangs', 'SMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Utah Utes', 'UTAH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Florida State Seminoles', 'FSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Eastern Kentucky Colonels', 'EKY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Army Black Knights', 'ARMY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Boise State Broncos', 'BSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southern Miss Golden Eagles', 'USM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Auburn Tigers', 'AUB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wagner Seahawks', 'WAG');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Fresno State Bulldogs', 'FRES');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UCLA Bruins', 'UCLA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Alabama Crimson Tide', 'ALA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Indiana State Sycamores', 'INST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Oregon Ducks', 'ORE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Morgan State Bears', 'MORG');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Purdue Boilermakers', 'PUR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Duke Blue Devils', 'DUKE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Eastern Illinois Panthers', 'EIU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Louisville Cardinals', 'LOU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Baylor Bears', 'BAY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Washington Huskies', 'WASH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Washington State Cougars', 'WSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Toledo Rockets', 'TOL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'California Golden Bears', 'CAL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'South Carolina Gamecocks', 'SC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southeast Missouri State Redhawks', 'SEMO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Marshall Thundering Herd', 'MRSH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Savannah State Tigers', 'SAV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Florida Atlantic Owls', 'FAU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Louisiana Tech Bulldogs', 'LT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UTSA Roadrunners', 'UTSA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southern University Jaguars', 'SOU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Northern Colorado Bears', 'UNCO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas A&M Aggies', 'TA&M');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Kentucky Wildcats', 'UK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tennessee-Martin Skyhawks', 'UTM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Virginia Tech Hokies', 'VT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'New Mexico State Aggies', 'NMSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wyoming Cowboys', 'WYO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Lamar Cardinals', 'LAMR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Rutgers Scarlet Knights', 'RUTG');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Arkansas Razorbacks', 'ARK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Georgia State Panthers', 'GAST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Liberty Flames', 'LIB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Boston College Eagles', 'BC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Miami (FL) Hurricanes', 'MIA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Michigan Wolverines', 'MICH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UTEP Miners', 'UTEP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Connecticut Huskies', 'CONN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Presbyterian Blue Hose', 'PRE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Samford Bulldogs', 'SAM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Elon Phoenix', 'ELON');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Middle Tennessee Blue Raiders', 'MTU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Illinois Fighting Illini', 'ILL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Oklahoma Sooners', 'OKLA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Florida A&M Rattlers', 'FAMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Western Michigan Broncos', 'WMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Navy Midshipmen', 'NAVY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Murray State Racers', 'MURR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Appalachian State Mountaineers', 'APP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Missouri Tigers', 'MIZZ');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tulane Green Wave', 'TULN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Stephen F. Austin Lumberjacks', 'SFA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Kansas State Wildcats', 'KSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Georgia Southern Eagles', 'GASO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Austin Peay Governors', 'PEAY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Colorado Buffaloes', 'COLO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Florida Gators', 'FLA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Western Carolina Catamounts', 'WCU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Youngstown State Penguins', 'YSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'McNeese State Cowboys', 'MCNS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Georgia Bulldogs', 'UGA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Ohio State Buckeyes', 'OSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'West Virginia Mountaineers', 'WVU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Air Force Falcons', 'AFA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Colorado State Rams', 'CSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wofford Terriers', 'WOF');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Ole Miss Rebels', 'MISS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Eastern Washington Eagles', 'EWU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Houston Cougars', 'HOU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Kent State Golden Flashes', 'KENT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'South Dakota State Jackrabbits', 'SDST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'San Diego State Aztecs', 'SDSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Iowa Hawkeyes', 'IOWA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Nebraska Cornhuskers', 'NEB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Iowa State Cyclones', 'ISU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southern Utah Thunderbirds', 'SUU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Chattanooga Mocs', 'CHAT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Nevada Wolf Pack', 'NEV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas Longhorns', 'TEX');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Temple Owls', 'TEM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Arizona State Sun Devils', 'ASU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Notre Dame Fighting Irish', 'ND');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Alabama A&M Bulldogs', 'AAMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'East Carolina Pirates', 'ECU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Massachusetts Minutemen', 'UMAS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Grambling State Tigers', 'GRAM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Northwestern Wildcats', 'NW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Texas Mean Green', 'UNT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Minnesota Golden Gophers', 'MINN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Central Arkansas Bears', 'CARK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Carolina Tar Heels', 'UNC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'New Hampshire Wildcats', 'UNH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Northern Iowa Panthers', 'UNI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'New Mexico Lobos', 'UNM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Memphis Tigers', 'MEM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wisconsin Badgers', 'WIS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Kansas Jayhawks', 'KU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Miami (OH) RedHawks', 'M-OH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'South Florida Bulls', 'USF');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'USC Trojans', 'USC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Michigan State Spartans', 'MSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Cincinnati Bearcats', 'CIN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UNLV Rebels', 'UNLV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Stanford Cardinal', 'STAN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Utah State Aggies', 'USU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Ball State Cardinals', 'BALL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Oregon State Beavers', 'ORST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Arkansas State Red Wolves', 'ARST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas A&M-Commerce Lions', 'TXA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UCF Knights', 'UCF');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UC Davis Aggies', 'UCD');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Ohio Bobcats', 'OHIO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Buffalo Bulls', 'BUFF');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Missouri State Bears', 'MOSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Howard Bison', 'HOW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Troy Trojans', 'TROY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'William & Mary Tribe', 'W&M');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wake Forest Demon Deacons', 'WAKE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', "Louisiana-Lafayette Ragin' Cajuns", 'ULL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Louisiana-Monroe Warhawks', 'ULM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'South Alabama Jaguars', 'USA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Carolina State Wolfpack', 'NCST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Southeastern Louisiana Lions', 'SELA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Jacksonville State Gamecocks', 'JVST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Nicholls State Colonels', 'NICH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Western Kentucky Hilltoppers', 'WKU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Colgate Raiders', 'COLG');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Carolina Central Eagles', 'NCCU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Norfolk State Spartans', 'NORF');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'South Dakota Coyotes', 'SDAK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', "Gardner-Webb Runnin' Bulldogs", 'WEBB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Prairie View A&M Panthers', 'PV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'James Madison Dukes', 'JMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Old Dominion Monarchs', 'ODU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Alcorn State Braves', 'ALCN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Western Illinois Leathernecks', 'WIU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Fordham Rams', 'FOR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Cal Poly Mustangs', 'CP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Stony Brook Seawolves', 'STON');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Delaware Fightin Blue Hens', 'DEL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Bethune-Cookman Wildcats', 'COOK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tennessee Tech Golden Eagles', 'TNTC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Campbell Fighting Camels', 'CAMP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Furman Paladins', 'FUR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Abilene Christian Wildcats', 'ACU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Hampton Pirates', 'HAMP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Montana State Bobcats', 'MTST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Portland State Vikings', 'PRST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Charlotte 49ers', 'CHAR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Mississippi Valley State Delta Devils', 'MVSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'San Diego Toreros', 'USD');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Stetson Hatters', 'STET');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Citadel Bulldogs', 'CIT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Houston Baptist Huskies', 'HBU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Holy Cross Crusaders', 'HC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Mercer Bears', 'MERC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Sacred Heart Pioneers', 'SHU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Pikeville Bears', 'PIK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Robert Morris Colonials', 'RMU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Alabama State Hornets', 'ALST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Monmouth Hawks', 'MONM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Montana Grizzlies', 'MONT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Butler Bulldogs', 'BUT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Arkansas-Pine Bluff Golden Lions', 'ARPB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Drake Bulldogs', 'DRKE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Marist Red Foxes', 'MRST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Georgetown Hoyas', 'GTWN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Eastern Oregon Mountaineers', 'EAS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Charleston Southern Buccaneers', 'CHSO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Dayton Flyers', 'DAY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Grand View Vikings', 'GV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Central Connecticut State Blue Devils', 'CCSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Coastal Carolina Chanticleers', 'CCAR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Rhode Island Rams', 'URI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Albany Great Danes', 'ALBY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Dakota', 'UND');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Duquesne Dukes', 'DUQ');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Cumberland Bulldogs', 'CUM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Valparaiso Crusaders', 'VALP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Jacksonville Dolphins', 'JAC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tennessee State Tigers', 'TNST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'OK Panhandle St Aggies', 'OKP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Langston Lions', 'LAN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Bryant Bulldogs', 'BRY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Virginia Military Institute Keydets', 'VMI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Warner Royals', 'UWS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'South Carolina State Bulldogs', 'SCST');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Edward Waters Tigers', 'EDW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Reinhardt Eagles', 'REIN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Morehead State Eagles', 'MORE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Concordia (AL) Hornets', 'CON');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Incarnate Word Cardinals', 'INC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Columbia Lions', 'CLMB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Colorado State-Pueblo Thunderwolves', 'COS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Cornell Big Red', 'COR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Benedict Tigers', 'BEN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Texas College Steers', 'TXCL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Princeton Tigers', 'PRIN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Carnegie Mellon Tartans', 'CAR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Lincoln (PA) Lions', 'LIN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Glenville State Pioneers', 'GLE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'William Jewell College Cardinals', 'WJC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Campbellsville Tigers', 'CAI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Dixie State Red Storm', 'DIX');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Bacone College Warriors', 'BAC');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Greenville Crusaders', 'NGR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Berry College Vikings', 'BER');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Harvard Crimson', 'HARV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Franklin Grizzlies', 'FRA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Assumption Greyhounds', 'ASP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tarleton State Texans', 'TAR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Salve Regina Seahawks', 'SAL');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Humboldt State Lumberjacks', 'HUM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Kentucky Wesleyan Panthers', 'KYW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'WV Wesleyan Bobcats', 'WVW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Davidson Wildcats', 'DAV');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'New Mexico Highlands Cowboys', 'NME');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Yale Bulldogs', 'YALE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Johnson Smith Golden Bulls', 'JOH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Pennsylvania Quakers', 'PENN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Lynchburg Hornets', 'LYN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Birmingham-Southern Panthers', 'BIR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Carolina A&T; Aggies', 'NCAT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Pittsburg State Gorillas', 'PIT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Charleston (WV) Golden Eagles', 'CHA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'St. Francis (PA) Red Flash', 'SFPA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Brown Bears', 'BRWN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', "St. Augustine's Falcons", 'STA');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Urbana Blue Knights', 'URB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Clark Atlanta Panthers', 'CLK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Delaware State Hornets', 'DSU');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Stillman Tigers', 'STI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', "St. Joseph's (IN) Pumas", 'STJ');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Chowan Braves', 'CHO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wesley College Wolverines', 'WES');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Angelo State Rams', 'ANG');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Ferris State Bulldogs', 'FER');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wayland Baptist Pioneers', 'WAY');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Point University Chargers', 'POI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Dartmouth Big Green', 'DART');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Virginia-Wise Highland Cavaliers', 'VAW');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Shorter Hawks', 'SHO');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Bucknell Bison', 'BUCK');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'McMurry War Hawks', 'MCM');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Mars Hill Lions', 'MAR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Florida Tech Panthers', 'FLTH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Lehigh Mountain Hawks', 'LEH');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Morehouse Tigers', 'MOR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Lafayette Leopards', 'LAF');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Tuskegee Golden Tigers', 'TUS');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Oklahoma Baptist Bison', 'OB');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Lenoir-Rhyne Bears', 'LEN');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Virginia Union Panthers', 'VIR');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'UNC Pembroke Braves', 'NCP');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Wittenberg Tigers', 'WIT');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Colorado Mesa Mavericks', 'MES');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Merrimack Warriors', 'MER');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Quincy Hawks', 'QUI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Central State Marauders', 'CCI');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'Brevard College Tornados', 'BRE');
INSERT INTO teams (sport, full, short) VALUES ('ncf', 'North Alabama Lions', 'NOR');
/* NCB */
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southern Illinois Salukis', 'SIU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cleveland State Vikings', 'CLEV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Sam Houston State Bearkats', 'SHSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Siena Saints', 'SIE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Clemson Tigers', 'CLEM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Dakota State Bison', 'NDSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'West Virginia Mountaineers', 'WVU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UC Riverside Highlanders', 'UCRV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Monmouth Hawks', 'MONM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Pittsburgh Panthers', 'PITT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Arkansas-Pine Bluff Golden Lions', 'ARPB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Drake Bulldogs', 'DRKE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UAB Blazers', 'UAB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Mississippi State Bulldogs', 'MSST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Carolina A&T Aggies', 'NCAT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'George Washington Colonials', 'GW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Drexel Dragons', 'DREX');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Georgia Tech Yellow Jackets', 'GT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Vanderbilt Commodores', 'VAN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Florida International Golden Panthers', 'FIU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Coastal Carolina Chanticleers', 'CCAR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Evansville Aces', 'EVAN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Green Bay Phoenix', 'GB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Bowling Green Falcons', 'BGSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Lafayette Leopards', 'LAF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'McNeese State Cowboys', 'MCNS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "Saint Joseph's Hawks", 'JOES');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Richmond Spiders', 'RICH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Rice Owls', 'RICE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas A&M-CC Islanders', 'AMCC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'La Salle Explorers', 'LAS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Belmont Bruins', 'BEL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Western Carolina Catamounts', 'WCU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UCLA Bruins', 'UCLA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Illinois State Redbirds', 'ILST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Central Michigan Chippewas', 'CMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'USC Upstate Spartans', 'SCUS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Utah Valley Wolverines', 'UVU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas Tech Red Raiders', 'TTU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'LSU Tigers', 'LSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Vermont Catamounts', 'UVM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Virginia Cavaliers', 'UVA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Delaware State Hornets', 'DSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Tulsa Golden Hurricane', 'TLSA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UMKC Kangaroos', 'UMKC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Bethune-Cookman Wildcats', 'COOK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Maine Black Bears', 'ME');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Maryland Terrapins', 'MD');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Quinnipiac Bobcats', 'QUIN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Tennessee Volunteers', 'TENN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Long Beach State 49ers', 'LBSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Indiana Hoosiers', 'IND');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "Gardner-Webb Runnin' Bulldogs", 'WEBB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Akron Zips', 'AKR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southern Methodist Mustangs', 'SMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Utah Utes', 'UTAH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Benedictine Eagles', 'BENE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Eastern Kentucky Colonels', 'EKY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "Saint Mary's Gaels",'SMC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wofford Terriers', 'WOF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Boise State Broncos', 'BSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Montana Grizzlies', 'MONT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Auburn Tigers', 'AUB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "St. Peter's Peacocks", 'SPC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Oral Roberts Golden Eagles', 'ORU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Loyola Marymount Lions', 'LMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Alabama Crimson Tide', 'ALA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Marquette Golden Eagles', 'MARQ');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Indiana State Sycamores', 'INST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Oregon Ducks', 'ORE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'San Francisco Dons', 'SF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Purdue Boilermakers', 'PUR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Duke Blue Devils', 'DUKE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Stetson Hatters', 'STET');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Baylor Bears', 'BAY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Canisius Golden Griffins', 'CAN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Toledo Rockets', 'TOL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'California Golden Bears', 'CAL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southeast Missouri State Redhawks', 'SEMO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'South Carolina Gamecocks', 'SCAR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Marshall Thundering Herd', 'MRSH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Maryland-Eastern Shore Hawks', 'UMES');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Louisiana Tech Bulldogs', 'LT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UTSA Roadrunners', 'UTSA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Marist Red Foxes', 'MRST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Brigham Young Cougars', 'BYU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas A&M Aggies', 'TA&M');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Kent State Golden Flashes', 'KENT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Nebraska-Omaha Mavericks', 'NEOM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Binghamton Bearcats', 'BING');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Arkansas State Red Wolves', 'ARST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Rutgers Scarlet Knights', 'RUTG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Hampton Pirates', 'HAMP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Miami (FL) Hurricanes', 'MIA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'LIU Brooklyn Blackbirds', 'LIU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Lipscomb Bisons', 'LIP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Michigan Wolverines', 'MICH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UTEP Miners', 'UTEP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Presbyterian Blue Hose', 'PRE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Radford Highlanders', 'RAD');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Samford Bulldogs', 'SAM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Sacramento State Hornets', 'SAC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Longwood Lancers', 'LONG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Yale Bulldogs', 'YALE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Savannah State Tigers', 'SAV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'St. Francis (NY) Terriers', 'SFNY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Lamar Cardinals', 'LAM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Rhode Island Rams', 'URI');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Chicago State Cougars', 'CHS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'SIU-Edwardsville Cougars', 'SIUE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Murray State Racers', 'MURR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Jacksonville Dolphins', 'JAC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Appalachian State Mountaineers', 'APP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Stony Brook Seawolves', 'STON');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Missouri Tigers', 'MIZZ');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Arkansas-Little Rock Trojans', 'UALR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Stephen F. Austin Lumberjacks', 'SFA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Kansas State Wildcats', 'KSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Furman Paladins', 'FUR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Georgia Southern Eagles', 'GASO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Austin Peay Governors', 'PEAY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Colorado Buffaloes', 'COLO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Stanford Cardinal', 'STAN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Colgate Raiders', 'COLG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Georgia State Panthers', 'GAST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Youngstown State Penguins', 'YSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Georgia Bulldogs', 'UGA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Charleston Southern Buccaneers', 'CHSO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cal State Northridge Matadors', 'CSN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Sacred Heart Pioneers', 'SHU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cal State Fullerton Titans', 'CSF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Air Force Falcons', 'AFA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cal State Bakersfield Roadrunners', 'CSB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wright State Raiders', 'WRST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Colorado State Rams', 'CSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Tennessee-Martin Skyhawks', 'UTM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Tennessee State Tigers', 'TNST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Charleston Cougars', 'COFC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Providence Friars', 'PROV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Creighton Bluejays', 'CREI');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UC Santa Barbara Gauchos', 'UCSB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Manhattan Jaspers', 'MAN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'South Dakota State Jackrabbits', 'SDST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'San Diego State Aztecs', 'SDSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Iowa Hawkeyes', 'IOWA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Iowa State Cyclones', 'ISU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northeastern Huskies', 'NE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Charlotte 49ers', 'CHAR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Chattanooga Mocs', 'CHAT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Elon Phoenix', 'ELON');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Gonzaga Bulldogs', 'GONZ');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Arizona State Sun Devils', 'ASU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Robert Morris Colonials', 'RMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'South Dakota Coyotes', 'SDAK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Alabama A&M Bulldogs', 'AAMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'East Carolina Pirates', 'ECU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Massachusetts Minutemen', 'UMAS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Seattle Redhawks', 'SEA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Texas Mean Green', 'UNT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Colby College White Mules', 'CLB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Central Arkansas Bears', 'CARK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Iona Gaels', 'IONA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Dakota', 'UND');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Florida Ospreys', 'UNF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'New Hampshire Wildcats', 'UNH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Duquesne Dukes', 'DUQ');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'New Mexico Lobos', 'UNM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'New Orleans Privateers', 'UNO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Virginia Military Keydets', 'VMI');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Kansas Jayhawks', 'KU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Alcorn State Braves', 'ALCN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Tennessee Tech Golden Eagles', 'TNTC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Mississippi Valley State Delta Devils', 'MVSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Oregon State Beavers', 'ORST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Campbell Fighting Camels', 'CAMP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UCF Knights', 'UCF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UC Davis Aggies', 'UCD');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Carolina Central Eagles', 'NCCU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UC Irvine Anteaters', 'UCI');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Buffalo Bulls', 'BUFF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Milwaukee Panthers', 'MILW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Saint Louis Billikens', 'SLU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Coppin State Eagles', 'COPP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'William & Mary Tribe', 'W&M');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Virginia Commonwealth Rams', 'VCU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'East Tennessee State Buccaneers', 'ETSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Arkansas Razorbacks', 'ARK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'N.J.I.T. Highlanders', 'NJIT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Jacksonville State Gamecocks', 'JVST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Nicholls State Colonels', 'NICH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Carolina Tar Heels', 'UNC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Western Kentucky Hilltoppers', 'WKU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'San Jose State Spartans', 'SJSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Pacific Tigers', 'PAC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northern Iowa Panthers', 'UNI');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Liberty Flames', 'LIB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Arizona Wildcats', 'ARIZ');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Idaho Vandals', 'IDHO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Rider Broncs', 'RID');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Weber State Wildcats', 'WEB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Pepperdine Waves', 'PEPP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Valparaiso Crusaders', 'VALP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Hawaii Warriors', 'HAW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Syracuse Orange', 'SYR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Norfolk State Spartans', 'NORF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UMBC Retrievers', 'UMBC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Towson Tigers', 'TOWS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northern Illinois Huskies', 'NIU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Eastern Michigan Eagles', 'EMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Fairleigh Dickinson Knights', 'FDU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Portland Pilots', 'PORT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Prairie View A&M Panthers', 'PV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'TCU Horned Frogs', 'TCU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas State Bobcats', 'TXST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Butler Bulldogs', 'BUT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Oklahoma State Cowboys', 'OKST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas Southern Tigers', 'TXSO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northwestern State Demons', 'NWST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'St. Francis (PA) Red Flash', 'SFPA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Fordham Rams', 'FOR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Villanova Wildcats', 'VILL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Jackson State Tigers', 'JKST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Seton Hall Pirates', 'HALL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Idaho State Bengals', 'IDST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Penn State Nittany Lions', 'PSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cornell Big Red', 'COR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Illinois Fighting Illini', 'ILL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Florida State Seminoles', 'FSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Harvard Crimson', 'HARV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Hartford Hawks', 'HART');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Army Black Knights', 'ARMY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Pennsylvania Quakers', 'PENN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Michigan State Spartans', 'MSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Ball State Cardinals', 'BALL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Fairfield Stags', 'FAIR');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Bucknell Bison', 'BUCK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wagner Seahawks', 'WAG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Fresno State Bulldogs', 'FRES');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cal Poly Mustangs', 'CP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Utah State Aggies', 'USU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Morgan State Bears', 'MORG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Morehead State Eagles', 'MORE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Eastern Illinois Panthers', 'EIU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Portland State Vikings', 'PRST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Washington Huskies', 'WASH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Washington State Cougars', 'WSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Louisville Cardinals', 'LOU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'American University Eagles', 'AMER');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Carolina-Wilmington Seahawks', 'UNCW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Florida Atlantic Owls', 'FAU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UNC Greensboro Spartans', 'UNCG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southern University Jaguars', 'SOU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UNC-Asheville Bulldogs', 'UNCA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wichita State Shockers', 'WICH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northern Colorado Bears', 'UNCO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Loyola (IL) Ramblers', 'L-IL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas-Arlington Mavericks', 'UTA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Middle Tennessee Blue Raiders', 'MTU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Virginia Tech Hokies', 'VT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Western Michigan Broncos', 'WMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'New Mexico State Aggies', 'NMSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Florida Gulf Coast Eagles', 'FGCU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wyoming Cowboys', 'WYO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'IUPUI Jaguars', 'IUPU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Columbia Lions', 'CLMB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Boston College Eagles', 'BC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Oakland Golden Grizzlies', 'OAK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Dartmouth Big Green', 'DART');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Boston University Terriers', 'BU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northern Arizona Lumberjacks', 'NAU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Houston Baptist Huskies', 'HBU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Connecticut Huskies', 'CONN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Illinois-Chicago Flames', 'UIC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Hardin-Simmons Cowboys', 'HSIM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Oklahoma Sooners', 'OKLA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Florida A&M Rattlers', 'FAMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Xavier Musketeers', 'XAV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Albany Great Danes', 'ALBY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Navy Midshipmen', 'NAVY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Tulane Green Wave', 'TULN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'DePaul Blue Demons', 'DEP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'High Point Panthers', 'HP');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Detroit Titans', 'DET');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Delaware Fightin Blue Hens', 'DEL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Denver Pioneers', 'DEN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Florida Gators', 'FLA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Holy Cross Crusaders', 'HC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'IPFW Mastodons', 'IPFW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Ohio State Buckeyes', 'OSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'James Madison Dukes', 'JMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Georgetown Hoyas', 'GTWN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Santa Clara Broncos', 'SCU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Ole Miss Rebels', 'MISS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Eastern Washington Eagles', 'EWU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'South Carolina State Bulldogs', 'SCST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Kennesaw State Owls', 'KENN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Kentucky Wildcats', 'UK');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Nebraska Cornhuskers', 'NEB');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southern Utah Thunderbirds', 'SUU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Nevada Wolf Pack', 'NEV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Temple Owls', 'TEM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Notre Dame Fighting Irish', 'ND');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Old Dominion Monarchs', 'ODU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas Longhorns', 'TEX');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Grambling State Tigers', 'GRAM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Central Connecticut State Blue Devils', 'CCSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northwestern Wildcats', 'NW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Loyola (MD) Greyhounds', 'L-MD');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Minnesota Golden Gophers', 'MINN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Brown Bears', 'BRWN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "St. John's Red Storm", 'SJU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Memphis Tigers', 'MEM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'George Mason Patriots', 'GMU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Bryant University Bulldogs', 'BRY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Lehigh Mountain Hawks', 'LEH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Winthrop Eagles', 'WIN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Western Illinois Leathernecks', 'WIU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wisconsin Badgers', 'WIS');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Mercer Bears', 'MER');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Niagara Purple Eagles', 'NIAG');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Miami (OH) RedHawks', 'M-OH');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'South Florida Bulls', 'USF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'San Diego Toreros', 'USD');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'USC Trojans', 'USC');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'South Alabama Jaguars', 'USA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southern Miss Golden Eagles', 'USM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Cincinnati Bearcats', 'CIN');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Montana State Bobcats', 'MTST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'UNLV Rebels', 'UNLV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "Mount St. Mary's Mountaineers", 'MSM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Citadel Bulldogs', 'CIT');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Alabama State Hornets', 'ALST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'St. Bonaventure Bonnies', 'SBON');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Davidson Wildcats', 'DAV');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Ohio Bobcats', 'OHIO');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Dayton Flyers', 'DAY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Hofstra Pride', 'HOF');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Missouri State Bears', 'MOSU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Howard Bison', 'HOW');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Troy Trojans', 'TROY');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Houston Cougars', 'HOU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Wake Forest Demon Deacons', 'WAKE');
INSERT INTO teams (sport, full, short) VALUES ('ncb', "Louisiana-Lafayette Ragin' Cajuns", 'ULL');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Louisiana-Monroe Warhawks', 'ULM');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'North Carolina State Wolfpack', 'NCST');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Southeastern Louisiana Lions', 'SELA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Northern Kentucky Norse', 'NKU');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Texas-Pan American Broncs', 'UTPA');
INSERT INTO teams (sport, full, short) VALUES ('ncb', 'Bradley Braves', 'BRAD');
